import { randomUUID } from "node:crypto"
import { afterAll, beforeAll, describe, expect, it } from "vitest"
import { AppError, QUEUES, type PresignedUpload } from "@speaking-track/contracts"
import {
  StorageObjectNotFoundError,
  createStorage,
  createStorageConfig,
  recordingObjectKeyFor,
  type StorageClient,
} from "../src/index"
import { loadRootEnv, mediaFixture, type TestEnv } from "./helpers"

/**
 * Storage behavior against the real Compose MinIO instance (private bucket,
 * anonymous access disabled). Uses small generated byte fixtures only.
 */

const BUCKET_OWNER = randomUUID()

function testEnv(env: TestEnv, overrides: Partial<TestEnv> = {}): TestEnv {
  // Both endpoints point at the host-bound MinIO for round-trip tests; the
  // presign-host test below exercises separate public endpoints explicitly.
  return {
    ...env,
    S3_INTERNAL_ENDPOINT: "http://127.0.0.1:9000",
    S3_PUBLIC_ENDPOINT: "http://127.0.0.1:9000",
    S3_FORCE_PATH_STYLE: "true",
    PRESIGNED_UPLOAD_TTL_SECONDS: "300",
    MAX_RECORDING_BYTES: "100000",
    MAX_STAGING_BYTES: "1000000",
    ...overrides,
  }
}

let storage: StorageClient

beforeAll(async () => {
  const env = testEnv(await loadRootEnv())
  storage = createStorage(createStorageConfig(env))
})

afterAll(() => {
  storage?.close()
})

describe("provider configuration validation", () => {
  it("rejects missing variables with a ConfigurationError naming them", async () => {
    const env = await loadRootEnv()
    expect(() => createStorageConfig({})).toThrowError(/S3_PUBLIC_ENDPOINT|S3_BUCKET/)
    expect(() => createStorageConfig({ ...testEnv(env), S3_BUCKET: "Bad_Bucket!" })).toThrowError(
      /S3_BUCKET/,
    )
    expect(() =>
      createStorageConfig({ ...testEnv(env), S3_INTERNAL_ENDPOINT: "ftp://nope" }),
    ).toThrowError(/S3_INTERNAL_ENDPOINT/)
    expect(() =>
      createStorageConfig({ ...testEnv(env), PRESIGNED_UPLOAD_TTL_SECONDS: "700000" }),
    ).toThrowError(/PRESIGNED_UPLOAD_TTL_SECONDS/)
    expect(() =>
      createStorageConfig({ ...testEnv(env), MAX_RECORDING_BYTES: "not-a-number" }),
    ).toThrowError(/MAX_RECORDING_BYTES/)
  })

  it("parses all documented storage variables", async () => {
    const env = await loadRootEnv()
    const config = createStorageConfig(testEnv(env))
    expect(config.bucket).toBe(env.S3_BUCKET)
    expect(config.forcePathStyle).toBe(true)
    expect(config.presignedUploadTtlSeconds).toBe(300)
    expect(config.maxRecordingBytes).toBe(100000)
  })
})

describe("object key generation", () => {
  it("uses the exact recordings/<owner>/<recording>/source.<ext> format", () => {
    const ownerId = randomUUID()
    const recordingId = randomUUID()
    expect(
      recordingObjectKeyFor({ ownerId, recordingId, mimeType: "video/webm;codecs=vp9,opus" }),
    ).toBe(`recordings/${ownerId}/${recordingId}/source.webm`)
    expect(recordingObjectKeyFor({ ownerId, recordingId, mimeType: "video/mp4" })).toBe(
      `recordings/${ownerId}/${recordingId}/source.mp4`,
    )
  })
})

describe("presigned upload against a separate public endpoint", () => {
  it("signs the URL for the public endpoint hostname, not the internal one", async () => {
    const env = await loadRootEnv()
    const separate = createStorage(
      createStorageConfig(testEnv(env, { S3_PUBLIC_ENDPOINT: "https://s3.public.example" })),
    )
    try {
      const upload = await separate.createPresignedUpload({
        ownerId: randomUUID(),
        recordingId: randomUUID(),
        mimeType: "video/webm;codecs=vp9,opus",
        sizeBytes: 10,
      })
      expect(upload.url.startsWith("https://s3.public.example/")).toBe(true)
      expect(upload.url).not.toContain("127.0.0.1")
    } finally {
      separate.close()
    }
  })
})

describe("presigned upload, PUT, stat, stream, delete on real MinIO", () => {
  let upload: PresignedUpload
  const recordingId = randomUUID()
  const fixture = mediaFixture(2048)
  const mimeType = "video/webm;codecs=vp9,opus"

  it("creates a presigned PUT pinned to the generated key and content type", async () => {
    upload = await storage.createPresignedUpload({
      ownerId: BUCKET_OWNER,
      recordingId,
      mimeType,
      sizeBytes: fixture.byteLength,
    })
    expect(upload.method).toBe("PUT")
    expect(upload.objectKey).toBe(`recordings/${BUCKET_OWNER}/${recordingId}/source.webm`)
    expect(upload.headers).toEqual({ "Content-Type": mimeType })
    expect(upload.expiresAt).toBeTruthy()
  })

  it("rejects oversized files before creating any URL", async () => {
    await expect(
      storage.createPresignedUpload({
        ownerId: BUCKET_OWNER,
        recordingId: randomUUID(),
        mimeType,
        // maxRecordingBytes is 100000 in this suite
        sizeBytes: 100001,
      }),
    ).rejects.toMatchObject({ code: "RECORDING_TOO_LARGE" })
    await expect(
      storage.createPresignedUpload({
        ownerId: BUCKET_OWNER,
        recordingId: randomUUID(),
        mimeType: "video/avi" as never,
        sizeBytes: 10,
      }),
    ).rejects.toMatchObject({ code: "UNSUPPORTED_MEDIA_TYPE" })
  })

  it("rejects unsafe object keys at every operation", async () => {
    const badKey = "recordings/../../etc/passwd/source.webm"
    await expect(storage.statPrivateObject(badKey)).rejects.toMatchObject({
      code: "VALIDATION_FAILED",
    })
    await expect(storage.getPrivateObjectStream(badKey)).rejects.toMatchObject({
      code: "VALIDATION_FAILED",
    })
    await expect(storage.deletePrivateObject(badKey)).rejects.toMatchObject({
      code: "VALIDATION_FAILED",
    })
  })

  it("uploads the fixture with the signed headers and verifies metadata via stat", async () => {
    const response = await fetch(upload.url, {
      method: "PUT",
      headers: upload.headers,
      body: fixture,
    })
    expect(response.status).toBe(200)

    const stat = await storage.statPrivateObject(upload.objectKey)
    expect(stat.sizeBytes).toBe(fixture.byteLength)
    expect(stat.contentType).toBe(mimeType)
    expect(stat.etag.length).toBeGreaterThan(0)
  })

  it("rejects a PUT with a mismatched content type (signature is content-type bound)", async () => {
    const other = await storage.createPresignedUpload({
      ownerId: BUCKET_OWNER,
      recordingId: randomUUID(),
      mimeType,
      sizeBytes: 16,
    })
    const response = await fetch(other.url, {
      method: "PUT",
      headers: { "Content-Type": "video/mp4" },
      body: mediaFixture(16),
    })
    expect(response.status).toBe(403)
  })

  it("streams the private object back", async () => {
    const stream = await storage.getPrivateObjectStream(upload.objectKey)
    const chunks: Buffer[] = []
    for await (const chunk of stream) {
      chunks.push(Buffer.from(chunk as Uint8Array))
    }
    const body = Buffer.concat(chunks)
    expect(body.byteLength).toBe(fixture.byteLength)
    expect(body[0]).toBe(0x1a)
  })

  it("maps missing objects to the typed not-found error", async () => {
    const missingKey = `recordings/${BUCKET_OWNER}/${randomUUID()}/source.webm`
    await expect(storage.statPrivateObject(missingKey)).rejects.toBeInstanceOf(
      StorageObjectNotFoundError,
    )
    await expect(storage.getPrivateObjectStream(missingKey)).rejects.toBeInstanceOf(
      StorageObjectNotFoundError,
    )
    // Deleting a missing object succeeds (idempotent cleanup).
    await expect(storage.deletePrivateObject(missingKey)).resolves.toBeUndefined()
  })

  it("deletes the staged object", async () => {
    await storage.deletePrivateObject(upload.objectKey)
    await expect(storage.statPrivateObject(upload.objectKey)).rejects.toBeInstanceOf(
      StorageObjectNotFoundError,
    )
  })
})

describe("shared contract sanity from the storage surface", () => {
  it("storage errors carry application error codes where shared", () => {
    const error = new AppError("RECORDING_TOO_LARGE", "too big")
    expect(error.code).toBe("RECORDING_TOO_LARGE")
    expect(QUEUES.maintenance).toBe("maintenance")
  })
})
